### ISSUE TITLE
Love the idea... but can't get it working

### ISSUE THREAD

**Issue by tjementum** [isg/rdio#1]
Ok... I've only spend 2 minutes, and gave up. I'm using Chrome but I - and properly others - need step by step instructions.

I love the idea - and you deserve that none tech people can get the benefits of your hard work.

I've create the instructions for you, hoping you will correct them, and include them in your readme.md file.
1. Start by bookmarking this page - or any other random page, as we will change it later. In most browsers you press Cmd+D on Mac and Ctrl+D on Windows.
2. Name the bookmark "Sync Rdio collection to mobile" - we need to change the url too, but in most browsers this needs a few extra steps.
3. In the browsers bookmark manager find the bookmark you just created, and click "Edit".
4. Replace the url "https://github.com/isg/rdio" with the following Javascript - don't include the quotation marks - "javascript:(function(){var d=document,s=d.createElement('script'),t=d.body;s.src='https://raw.github.com/isg/rdio/master/agent.js';t.appendChild(s);})();"

Now... whenever you need to mark new items for mobile sync, do this:
1. Navigate to http://www.rdio.com
2. Ensure you are logged in
3. Click the collection link, so your browser is on the Collection page (eg. http://www.rdio.com/people/username/collection/)
4. Click the bookmark you created above.
5. If everything worked, you should see the orange icon on everything in your collection, indicating if that they are marked for mobile sync.

As I wrote in the beginning... it doesn't work for me, so I might have done it all wrong, and I don't know if I'm doing it wrong, or if you code is not working any more ;-)

**Comment by isg** [comment]
Sorry it took me so long to respond! Please try it again as it's possible you were using an outdated version. Make sure you copy the script in its entirety, exactly as it appears on the page. When you click the bookmark, you should see new options on the left side of the page. From there you can click to mark everything as available offline!

Let me know how it goes!
